ping script

diff --git a/.github/workflows/keep_alive.yaml b/.github/workflows/keep_alive.yaml
--- a/.github/workflows/keep_alive.yaml
+++ b/.github/workflows/keep_alive.yaml
@@ -9,10 +9,14 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Ping Backend (Main API)
-        run: curl -s --max-time 10 https://finqa-app.onrender.com/ || echo "Failed to ping backend main API"
+        run: |
+          curl -s --max-time 10 https://finqa-app.onrender.com/ || echo "Failed to ping backend main API"
+          curl -s --max-time 10 https://finqa-app-w15r.onrender.com/ || echo "Failed to ping backend main API"
 
       - name: Ping Backend (Auth API)
-        run: curl -s --max-time 10 https://finqa-auth-app.onrender.com/ || echo "Failed to ping backend auth API"
+        run: |
+          curl -s --max-time 10 https://finqa-auth-app.onrender.com/ || echo "Failed to ping backend auth API"
+          curl -s --max-time 10 https://finqa-auth-app-ac1o.onrender.com/ || echo "Failed to ping backend auth API"
 
       - name: Ping Frontend
         run: curl -s --max-time 10 https://finqaai.netlify.app/ || echo "Failed to ping frontend"
